---
title: "ggplot1"
author: "Ava Hamilton"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges) # only use for 1 thing: XXXXX


```


## download/manipulate data
```{r}

### downloads data (weather monitoring stations, then variables want, and then between two dates)
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```


## create a ggplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```



## alternative way of making this plot

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

```

##saving initial plots - jeff doesnt really use this

```{r}

scatter_plot = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

scatter_plot
```


### adding color

```{r}


weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.4) #alpha does some transparency

```

Why do 'aes' positions matter?
```{r}


weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + ### defines aesthetic mappings for everything that happens after it
  geom_point(aes(color = name), alpha = 0.4) + #color mapping only applies to geom_point. If want it to apply to geom_smooth then put it in ggplot aes
  geom_smooth(se = FALSE) #curve going through plot and se = FALSE gets rid of CI

```

```{r}

weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)

```


## this is fine but not interesting

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name))+
  geom_point(aes(size = prcp, alpha = 0.4))+ ## point change size based on precipitaiton
  geom_smooth(se = F)
```





